version: '3.7'
services:
  survey_editor:
    image: regfe89/survey_editor_backend:latest
    ports:
      - "8000:80"
    environment:
      - DBPASSWORD=
      - DBUSER=
    networks:
      survey_network:
        ipv4_address: 172.22.0.8

networks:
  survey_network:
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24